apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-frontend
  name: user-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-frontend
  template:
    metadata:
      labels:
        app: user-frontend
    spec:
      volumes:
        - name: user-frontend-volume
          configMap:
            name: user-frontend
      containers:
      - image: 34.100.182.114/call-booking-app/user-ui:3.0 #deekshithsn/user-ui-new:latest #deekshithsn/userui:1.0
        name: user-frontend
        ports:
          - name: http 
            containerPort: 3000
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 2000            
        # resources:
        #   requests:
        #     memory: "1Gi"
        #     cpu: "1"
        #   limits:
        #     memory: "1Gi"
        #     cpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1  
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1        
        volumeMounts:
          - name: user-frontend-volume
            mountPath: /app/.env
            subPath: .env
