apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-backend
  name: user-backend
  namespace: user-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-backend
  template:
    metadata:
      labels:
        app: user-backend
    spec:
      nodeSelector: 
        module: app
      containers:
      - image: 805417853753.dkr.ecr.us-east-1.amazonaws.com/user-api:latest
        name: user-backend
        ports:
          - name: http
            containerPort: 1025
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
        env:
        - name: MONGO_URL
          value: "mongodb://admin:admin@mongo-svc.mongo-db.svc.cluster.local/?retryWrites=true&w=majority"
        - name: ADMIN_EMAIL
          value: admin@deekshithsn.live
        - name: PORT
          value: "1025"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 1025
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1  
        readinessProbe:
          httpGet:
            path: /api/health
            port: 1025
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1
          