apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-backend
  name: user-backend-svc
  namespace: user-apps
spec:
  ports:
  - port: 1025
    protocol: TCP
    targetPort: http
    nodePort: 32000
  selector:
    app: user-backend
  type: NodePort