apiVersion: v1
kind: Secret
metadata:
  name: mongo-creds-ub
data:
  monogo_connection_string: bW9uZ29kYjovL2FkbWludXNlcjpwYXNzd29yZDEyM0Btb25nby1zdmMubW9uZ28tZGIvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==