apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admin-backend
  name: admin-backend
  namespace: admin-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-backend
  template:
    metadata:
      labels:
        app: admin-backend
    spec:
      nodeSelector: 
        module: app
      containers:
      - image: 805417853753.dkr.ecr.us-east-1.amazonaws.com/admin-api:latest
        name: admin-backend
        ports:
        - name: http 
          containerPort: 1025
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 2000
        env:
        - name: MONGO_URL
          value: "mongodb://admin:admin@mongo-svc.mongo-db.svc.cluster.local/?retryWrites=true&w=majority"
        - name: JWT_SECRET
          value: "secret"
        - name: PORT
          value: "1025"
        resources:
          requests:
            cpu: "250m"
            memory: "2Gi"
          limits:
            cpu: "500m"
            memory: "4Gi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 1025
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1  
        readinessProbe:
          httpGet:
            path: /api/health
            port: 1025
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1

          