apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admin-backend
  name: admin-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-backend
  template:
    metadata:
      labels:
        app: admin-backend
    spec:
      containers:
      - image: 34.100.182.114/call-booking-app/admin-api:3.0
        name: admin-backend
        ports:
        - name: http 
          containerPort: 1004
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 2000
        env:
        - name: MONGO_URL
          value: "mongodb://adminuser:password123@mongo-nodeport-svc/?retryWrites=true&w=majority"
        - name: JWT_SECRET
          value: "secret"
        # resources:
        #   requests:
        #     memory: "128Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "250m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 1004
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1  
        readinessProbe:
          httpGet:
            path: /api/health
            port: 1004
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1
          