apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-db
  namespace: mongo-db
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2



# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mongo-data-pv
# spec:
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 1Gi
#   hostPath:
#     path: /data/mongo