apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admin-frontend
  name: admin-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-frontend
  template:
    metadata:
      labels:
        app: admin-frontend
    spec:
      volumes:
        - name: admin-frontend-volume
          configMap:
            name: admin-frontend
      containers:
      - image: deekshithsn/adminui:1.0
        name: admin-frontend
        ports:
          - name: http 
            containerPort: 3000
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 2000            
        # resources:
        #   requests:
        #     memory: "1Gi"
        #     cpu: "1"
        #   limits:
        #     memory: "1Gi"
        #     cpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1  
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1  
        volumeMounts:
          - name: admin-frontend-volume
            mountPath: /app/.env
            subPath: .env
